-- ============================================================================
-- V_BAMBOO_NOT_IN_ACTIVTRAK
-- Active BambooHR employees present in Timelogs (TL_EMPLOYEES) with no
-- ActivTrak footprint in either TL_ATTENDANCE or TL_PRODUCTIVITY.
-- ============================================================================

CREATE OR REPLACE VIEW V_BAMBOO_NOT_IN_ACTIVTRAK AS
SELECT
  e.ID AS EMPLOYEE_ID,
  LOWER(e.EMAIL) AS EMAIL,
  NVL(
    e.DISPLAY_NAME,
    TRIM(NVL(e.FIRST_NAME, '') || ' ' || NVL(e.LAST_NAME, ''))
  ) AS DISPLAY_NAME,
  e.FIRST_NAME,
  e.LAST_NAME,
  e.JOB_TITLE,
  NVL(e.DEPARTMENT, 'Unknown') AS DEPARTMENT,
  NVL(e.DIVISION, 'Unknown') AS DIVISION,
  NVL(e.LOCATION, 'Unknown') AS LOCATION,
  e.SUPERVISOR_EMAIL,
  e.HIRE_DATE,
  e.STATUS,
  m.TBS_EMPLOYEE_NO,
  CASE
    WHEN t.EMPLOYEE_NO IS NULL THEN NULL
    ELSE TRIM(NVL(t.EMPLOYEE_FIRST_NAME, '') || ' ' || NVL(t.EMPLOYEE_LAST_NAME, ''))
  END AS TBS_EMPLOYEE_NAME,
  TRIM(t.EMPLOYEE_DEPT) AS TBS_DEPARTMENT
FROM TL_EMPLOYEES e
LEFT JOIN TL_TBS_EMPLOYEE_MAP m
  ON LOWER(m.EMAIL) = LOWER(e.EMAIL)
LEFT JOIN TBS_EMPLOYEES@TBS_LINK t
  ON t.EMPLOYEE_NO = m.TBS_EMPLOYEE_NO
WHERE e.EMAIL IS NOT NULL
  AND (e.STATUS IS NULL OR UPPER(e.STATUS) != 'INACTIVE')
  AND NOT EXISTS (
    SELECT 1
    FROM TL_ATTENDANCE a
    WHERE LOWER(a.EMAIL) = LOWER(e.EMAIL)
  )
  AND NOT EXISTS (
    SELECT 1
    FROM TL_PRODUCTIVITY p
    WHERE LOWER(p.EMAIL) = LOWER(e.EMAIL)
  );
